### PR TITLE
(4th) Submission of Stage (1)

### PR DESCRIPTION
**Pull request by Plouis53**
Some of the elements from the figma does not transfer well to my project like the layouts and typography.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Unfortunately there're not much changes since last review, so the most comments are the same. I added some screenshots for comments so you can check them and compare them with your project after fixes. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * The page should look similar with the mockup on 1440px (now it looks like it's 768px version, you should change the media-quieries https://pasteboard.co/6Mqkc9fQIPRX.png)
    * Incorrect height of the popup window on 320 viewport (top edge should be higher, and you need to add popup close button) https://pasteboard.co/y5bqFLq7T5kz.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Note, that all content of the page should be centered horizontally on intermediate screen resolutions https://pasteboard.co/qlST4kPJNEWC.png https://pasteboard.co/VaW0kxlCYBFx.png https://pasteboard.co/Bo6imIdJkzrL.png https://pasteboard.co/no9H0y95P6hP.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * All theme modifiers should be key-value modifiers, not boolean one. Please check and fix all similar cases throughout the project https://en.bem.info/methodology/quick-start/#key-value (you can see the example on the screenshot https://pasteboard.co/qmQuHuKQv7MB.png)
    * You shouldn't use BEM element class outside of its block (for example `block__element` class should be a child of the container with `block` class). Please check and fix all similar cases throughout the project. You can see the example on the screenshot https://pasteboard.co/qRJEDffPnyuG.png
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * It will be great to use `nav` tag for navigation blocks on both pages
    * `saved-news` page should have `header` and `h1` tags
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__search` button should have correct hover and active states
    * Show more button has incorrect hover state
    * Header tab links shouldn't change its opacity in hover state, only cursor
    * News card booking button has incorrect hover state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `nav`, `nav__logo`, `card__publisher`, `saved__title`, `saved__words` and `saved__header` elements should have alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by Plouis53** [comment]
I've made more updates. My last update was "added H1", which is my most recent update. And if that doesn't work, please review my website. (https://newsquest.mooo.com/). Have a goodnight!

**Comment by FiLLa-FaS** [comment]
Hi! I see that you've added `h1` tag, it's great! And some sections are centered correctly on intermediate screen resolutions. But there're still several things that should be fixed, I provided most of my comments with more detailed explanations and screeshots. Please don't forget to check all the project before submitting and make sure that none of the sections was broken after the fixes. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `about` section looks incorrectly on 768 viewport and 320 viewport https://pasteboard.co/34RYGFiqSAEQ.png https://pasteboard.co/IH8ZYmbS5Jjj.png
    * The page should look similar with the mockup on 1440px (now it looks like it's 768px version, you should change the media-quieries https://pasteboard.co/6Mqkc9fQIPRX.png)
    * Popup looks incorrectly on 320 viewport (there should be a small top space between the top scree edge and popup container and you need to add visible close button) https://pasteboard.co/TFcxGIsmj2FL.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Note, that all content of the page should be centered horizontally on intermediate screen resolutions https://pasteboard.co/IvH3vS3PQFq6.png https://pasteboard.co/H4DFOfj1meYJ.png https://pasteboard.co/HW6C5Wf395iS.png
    * `about` section looks incorrectly on intermediate screen resolutions - text content shouldn't be placed in narrow column with 1-2 words in a row  https://pasteboard.co/Qj4Xy0wO1Pmm.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * All theme modifiers should be key-value modifiers, not boolean one. Please check and fix all similar cases throughout the project https://en.bem.info/methodology/quick-start/#key-value (you can see the example on the screenshot https://pasteboard.co/qmQuHuKQv7MB.png)
    * You shouldn't use BEM element class outside of its block (for example `block__element` class should be a child of the container with `block` class). Please check and fix all similar cases throughout the project. You can see the example on the screenshot https://pasteboard.co/qRJEDffPnyuG.png
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * It will be great to use `nav` tag for navigation block in `header` section (we have `nav` block class and can use `nav` tag for these cases)
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__search` button should have correct hover and active states
    * Show more button has incorrect hover state
    * Header tab links shouldn't change its opacity in hover state, only cursor
    * News card booking button has incorrect hover state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `nav`, `nav__logo`, `card__publisher`, `saved__title`, `saved__words` and `saved__header` elements should have generic font-family (like in all other `font-family` styles)
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by FiLLa-FaS** [comment]
Hi! You've done a great job, project looks much better! However there're still some issues that we need to work on. Good luck ✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `about` section looks incorrectly on all breakpoints screen resolutions, you need to check side spaces of the section content, gaps between all items (especially between columns), font-family of `about__paragraph` and space between `about` and `footer` on all screen resolutions
    * The page should look similar with the mockup on 1440px (you need to check all sizes, spaces and text properties for both pages - you can see the examples on the screenshots https://pasteboard.co/NDU76rs01JSc.png https://pasteboard.co/EqOjb71ZfCGN.png)
    * Incorrect space between `saved__words` and `saved__container`, `saved__container` and  news cards on all screen resolutions
    * News cards looks incorrectly on 320 and 768 viewports - you shoudl check their width, height and spaces between cards
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Note, that all content of the page should be centered horizontally on intermediate screen resolutions (it means that side spaces should be equal to each other. You need to check all sections on all screen resolutions between 320px and 1440px)
    * The main page scrolls horizontally on 321px - 500px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * `nav__mobile_dark` and `nav__mobile_light` should be key-values modifiers instead of boolean
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__search` button should have correct hover and active states according to the design UI kit
    * News card booking button has incorrect hover state (you can find all correct states in UI kit of the figma page)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 68

**Comment by Plouis53** [comment]
Hey there! I made the required corrections, but I ended up encountering another issue. In my 330px view, the mobile menu is showing up on the main page, but it's not appearing in the saved articles profile.

**Comment by FiLLa-FaS** [comment]
Hi! I'm glad that you've fixed last issue with BEM classes and hover state for booking button. But nav menu looks a bit broken now and most of the project isn't centered correctly. Please make sure that all sections are centered horizontally on all screen resolutions (side spaces should be equal visually, note, that some broken layouts or using several different spaces in different places can effect on visual spaces and we should count centering only if we can see it correctly). Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Incorrect width of `header` and `footer` sections on 1440 viewport (but it's correct on 1441px)
    * The both pages look incorrectly on 768 viewport (some styles look like on 320 viewport https://pasteboard.co/SLs4hSYXtRcb.png, please check widths of all sections, sizes of images and logos and text properties of all items. And note, that there shouldn't be nav burger on 768 viewport)
    * Mobile nav menu looks broken on all screen resolutions https://pasteboard.co/cVFTX1b07d9H.png
    * No burger menu on `saved-articles` page on mobile screen resolutions
    * `about` section looks incorrectly on all breakpoints screen resolutions, you need to check side spaces of the section content, gaps between all items (especially between columns), font-family of `about__paragraph` and space between about and footer on all screen resolutions https://pasteboard.co/VkT7nYksMQfw.png
    * Incorrect space between `saved__words` and `saved__container`, `saved__container` and news cards on all screen resolutions https://pasteboard.co/xLRvpcWC78Ag.png
    * News cards looks incorrectly on 320 and 768 viewports - you should check their width, height and spaces between cards
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Main page scrolls horizontally on 321px - 500px, 682px - 725px screen resolutions
    * Note, that all content of the page should be centered horizontally on intermediate screen resolutions (it means that side spaces should be equal to each other. You need to check all sections on all screen resolutions between 320px and 1440px) https://pasteboard.co/W5otC7TD9NMI.png https://pasteboard.co/haG3uB6SqjSp.png https://pasteboard.co/V1jt6chjaDDq.png https://pasteboard.co/y91aQUqrsZA9.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__search` button should have correct hover and active states according to the design UI kit (currently its hover state looks like active state and there's no active state at all)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 72

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm very glad to accept your project! Btw you still can fix the rest issues below to make the project looks similar with the mockup on all screen resolutions. Good luck on the next stage!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Main page 1440px https://pasteboard.co/0WbcYsqgnHM6.png https://pasteboard.co/imei3YnPDQ9M.png
    * Main page 768px https://pasteboard.co/6V3wzaKtymXV.png https://pasteboard.co/A9g8IdoFOC03.png https://pasteboard.co/broJpMR2ohlo.png
    * Main page 320px https://pasteboard.co/2NzRluscIDL4.png https://pasteboard.co/FeMuO8orWFgO.png https://pasteboard.co/AHeD3CbirH5N.png
    * Saved-articles page on 1440px https://pasteboard.co/lWwinF4VkrEn.png https://pasteboard.co/L7Vput5QHvKI.png 
    * `saved-container` and news cards don't correspond the mockup on 320 and 768 viewports - you need to check layouts, sizes, spaces and text properties https://disk.yandex.ru/i/wan52SR4CqonAg https://disk.yandex.ru/i/fNFv60HxygV2nw
    * Popup looks incorrectly on 768 viewport - it looks similar with 320 viewport and should look differently
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__search` button should have correct hover and active states according to the design UI kit (currently its hover state looks like active state and there's no active state at all)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 85

**Pull request merged**
